version: '3.9'

services:
  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mirea
    ports:
      - 5434:5432